//! Hermes hook and plugin template generation.
//!
//! This module contains the Python code templates for:
//! 1. Gateway Event Hook (`~/.hermes/hooks/hub_bridge/`)
//! 2. Plugin (`~/.hermes/hermes-agent/plugins/hub-bridge/`)
//!
//! By centralizing templates here, both `agent-hook` CLI and `src-tauri`
//! share the same source of truth for Hermes integration code.

use std::path::PathBuf;

/// Gateway Event Hook YAML manifest.
pub const GATEWAY_HOOK_YAML: &str = r#"name: hub-bridge
description: Forward agent events to Diamond WS Hub
events:
  - gateway:startup
  - session:start
  - session:end
  - session:reset
  - agent:start
  - agent:step
  - agent:end
  - command:*
"#;

/// Plugin YAML manifest.
pub const PLUGIN_YAML: &str = r#"name: hub-bridge
version: 0.1.0
description: "Forward agent events to Diamond WS Hub for real-time monitoring"
author: "Diamond"
hooks:
  - pre_tool_call
  - post_tool_call
  - pre_llm_call
  - post_llm_call
  - transform_llm_output
  - on_session_start
  - on_session_end
"#;

/// Generate the Gateway Event Hook handler.py content.
pub fn generate_gateway_handler(hub_url: &str) -> String {
    let http_url = hub_url.replace("ws://", "http://").replace("/hook", "");

    format!(
        r##"# Hermes Gateway -> Diamond WS Hub bridge handler.
# Generated by Diamond agent-hook.

import json
import threading
from datetime import datetime

HUB_WS_URL = "{hub_url}"
HUB_HTTP_URL = "{http_url}"
FRAMEWORK = "hermes"

_ws = None
_connected = False
_buffer = []
_buffer_lock = threading.Lock()


def _connect_ws():
    global _ws, _connected
    try:
        import websocket
        _ws = websocket.WebSocket()
        _ws.connect(HUB_WS_URL)
        _connected = True
        _ws.send(json.dumps({{"framework": FRAMEWORK, "session_id": "hermes-gateway"}}))
        with _buffer_lock:
            while _buffer:
                _ws.send(_buffer.pop(0))
        print(f"[hub-bridge] Connected to {{HUB_WS_URL}}")
    except Exception as e:
        _connected = False


def _emit_ws(event_type, data):
    global _ws, _connected
    msg = json.dumps({{
        "event": event_type,
        "framework": FRAMEWORK,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "data": data or {{}},
    }})
    if _connected and _ws:
        try:
            _ws.send(msg)
        except Exception:
            _connected = False
            with _buffer_lock:
                _buffer.append(msg)
    else:
        with _buffer_lock:
            _buffer.append(msg)
            if len(_buffer) > 100:
                _buffer.pop(0)


def _emit_http(event_type, data):
    try:
        import urllib.request
        payload = json.dumps({{
            "event": event_type,
            "framework": FRAMEWORK,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "data": data or {{}},
        }}).encode()
        req = urllib.request.Request(
            f"{{HUB_HTTP_URL}}/api/emit",
            data=payload,
            headers={{"Content-Type": "application/json"}},
            method="POST"
        )
        urllib.request.urlopen(req, timeout=2)
    except Exception:
        pass


def emit(event_type, data=None):
    if _connected:
        _emit_ws(event_type, data)
    else:
        try:
            _connect_ws()
            if _connected:
                _emit_ws(event_type, data)
            else:
                _emit_http(event_type, data)
        except Exception:
            _emit_http(event_type, data)


threading.Thread(target=_connect_ws, daemon=True).start()


async def handle(event_type, context):
    data = {{}}
    for key in ["session_id", "session_key", "platform", "user_id", "chat_id", "thread_id"]:
        if key in context:
            data[key] = context[key]
    if "message" in context and isinstance(context["message"], str):
        data["message"] = context["message"][:500]
    if "response" in context and isinstance(context["response"], str):
        data["response"] = context["response"][:500]
    if "iteration" in context:
        data["iteration"] = context["iteration"]
    if "tool_names" in context:
        data["tool_names"] = context["tool_names"]
    emit(event_type, data)
"##
    )
}

/// Generate the Plugin __init__.py content.
pub fn generate_plugin_init(hub_url: &str) -> String {
    let http_url = hub_url.replace("ws://", "http://").replace("/hook", "");

    format!(
        r##"# Hermes Plugin -> Diamond WS Hub bridge.
# Generated by Diamond agent-hook.
# Hooks into CLI/TUI mode via Hermes plugin system.

import json
import atexit
from datetime import datetime

HUB_HTTP_URL = "{http_url}"
FRAMEWORK = "hermes"


def emit(event_type, data=None):
    # Emit an event to the Hub via HTTP.
    try:
        import urllib.request
        payload = json.dumps({{
            "event": event_type,
            "framework": FRAMEWORK,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "data": data or {{}},
        }}).encode()
        req = urllib.request.Request(
            f"{{HUB_HTTP_URL}}/api/emit",
            data=payload,
            headers={{"Content-Type": "application/json"}},
            method="POST"
        )
        urllib.request.urlopen(req, timeout=5)
    except Exception as e:
        print(f"[hub-bridge] emit failed: {{e}}")


def _on_shutdown():
    # Emit gateway shutdown event when plugin is unloaded.
    try:
        emit("gateway:shutdown", {{"reason": "plugin_unload"}})
    except Exception:
        pass


# Register shutdown handler
atexit.register(_on_shutdown)


def register(ctx):
    # Called by Hermes plugin system to register hooks.
    print("[hub-bridge] Registering hooks...")
    ctx.register_hook("pre_tool_call", on_pre_tool_call)
    ctx.register_hook("post_tool_call", on_post_tool_call)
    ctx.register_hook("pre_llm_call", on_pre_llm_call)
    ctx.register_hook("post_llm_call", on_post_llm_call)
    ctx.register_hook("on_session_start", on_session_start)
    ctx.register_hook("on_session_end", on_session_end)
    ctx.register_hook("transform_llm_output", on_transform_llm_output)
    # Emit startup event
    emit("gateway:start", {{"version": "1.0.0"}})
    print("[hub-bridge] Hooks registered")


def _safe_str(val, max_len=500):
    if val is None:
        return None
    try:
        s = str(val)
        return s[:max_len] if len(s) > max_len else s
    except:
        return "<unserializable>"


def _safe_dict(d, max_val_len=300):
    if not d or not isinstance(d, dict):
        return {{}}
    result = {{}}
    for k, v in d.items():
        try:
            s = str(v)
            result[str(k)] = s[:max_val_len] if len(s) > max_val_len else s
        except:
            result[str(k)] = "<unserializable>"
    return result


def on_pre_tool_call(*args, **kwargs):
    try:
        tool_name = kwargs.get("tool_name", "")
        tool_args = kwargs.get("args", {{}})
        session_id = kwargs.get("session_id")
        task_id = kwargs.get("task_id")
        tool_call_id = kwargs.get("tool_call_id")

        if not tool_name and args:
            tool_name = args[0] if len(args) > 0 else ""
        if not tool_args and len(args) > 1:
            tool_args = args[1] if isinstance(args[1], dict) else {{}}

        emit("tool:start", {{
            "tool_name": _safe_str(tool_name, 100),
            "session_id": _safe_str(session_id, 100),
            "task_id": _safe_str(task_id, 100),
            "tool_call_id": _safe_str(tool_call_id, 100),
            "args": _safe_dict(tool_args),
        }})
    except Exception as e:
        print(f"[hub-bridge] pre_tool_call error: {{e}}")


def on_post_tool_call(*args, **kwargs):
    try:
        tool_name = kwargs.get("tool_name", "")
        tool_args = kwargs.get("args", {{}})
        result = kwargs.get("result")
        session_id = kwargs.get("session_id")
        task_id = kwargs.get("task_id")
        tool_call_id = kwargs.get("tool_call_id")
        duration_ms = kwargs.get("duration_ms")

        if not tool_name and args:
            tool_name = args[0] if len(args) > 0 else ""

        result_data = None
        if result is not None:
            try:
                result_data = json.loads(result) if isinstance(result, str) else result
            except (json.JSONDecodeError, TypeError):
                result_data = _safe_str(result, 500)

        emit("tool:complete", {{
            "tool_name": _safe_str(tool_name, 100),
            "session_id": _safe_str(session_id, 100),
            "task_id": _safe_str(task_id, 100),
            "tool_call_id": _safe_str(tool_call_id, 100),
            "duration_ms": duration_ms,
            "args": _safe_dict(tool_args),
            "result": result_data,
        }})
    except Exception as e:
        print(f"[hub-bridge] post_tool_call error: {{e}}")


def on_pre_llm_call(*args, **kwargs):
    try:
        session_id = kwargs.get("session_id")
        user_message = kwargs.get("user_message")
        model = kwargs.get("model")
        platform = kwargs.get("platform")
        is_first_turn = kwargs.get("is_first_turn")
        conversation_history = kwargs.get("conversation_history")

        emit("agent:start", {{
            "session_id": _safe_str(session_id, 100),
            "model": _safe_str(model, 100),
            "platform": _safe_str(platform, 50),
            "is_first_turn": is_first_turn,
            "user_message": _safe_str(user_message, 1000),
            "history_length": len(conversation_history) if conversation_history else 0,
        }})
    except Exception as e:
        print(f"[hub-bridge] pre_llm_call error: {{e}}")


def on_post_llm_call(*args, **kwargs):
    try:
        session_id = kwargs.get("session_id")
        model = kwargs.get("model")
        platform = kwargs.get("platform")

        emit("agent:end", {{
            "session_id": _safe_str(session_id, 100),
            "model": _safe_str(model, 100),
            "platform": _safe_str(platform, 50),
        }})
    except Exception as e:
        print(f"[hub-bridge] post_llm_call error: {{e}}")


def on_session_start(*args, **kwargs):
    try:
        session_id = kwargs.get("session_id")
        emit("session:start", {{"session_id": _safe_str(session_id, 100)}})
    except Exception as e:
        print(f"[hub-bridge] on_session_start error: {{e}}")


def on_session_end(*args, **kwargs):
    try:
        session_id = kwargs.get("session_id")
        emit("session:end", {{"session_id": _safe_str(session_id, 100)}})
    except Exception as e:
        print(f"[hub-bridge] on_session_end error: {{e}}")


def on_transform_llm_output(*args, **kwargs):
    # Capture the final response text.
    try:
        response_text = kwargs.get("response_text", "")
        session_id = kwargs.get("session_id")
        model = kwargs.get("model")
        platform = kwargs.get("platform")

        emit("assistant:response", {{
            "session_id": _safe_str(session_id, 100),
            "model": _safe_str(model, 100),
            "platform": _safe_str(platform, 50),
            "response_text": _safe_str(response_text, 5000),
        }})
        return None
    except Exception as e:
        print(f"[hub-bridge] transform_llm_output error: {{e}}")
        return None
"##
    )
}

/// Result of installing hooks for a framework.
#[derive(Debug, Clone)]
pub struct HookInstallResult {
    /// Path to the Gateway Event Hook directory.
    pub gateway_hook_dir: Option<PathBuf>,
    /// Path to the Plugin directory.
    pub plugin_dir: Option<PathBuf>,
    /// Whether the plugin was enabled in config.yaml.
    pub config_updated: bool,
    /// Any warnings encountered during installation.
    pub warnings: Vec<String>,
}

/// Install Hermes hooks (Gateway Event Hook + Plugin).
pub fn install_hermes_hooks(
    hermes_home: &std::path::Path,
    hub_url: &str,
) -> Result<HookInstallResult, String> {
    let mut result = HookInstallResult {
        gateway_hook_dir: None,
        plugin_dir: None,
        config_updated: false,
        warnings: Vec::new(),
    };

    // 1. Create Gateway Event Hook
    let hooks_dir = hermes_home.join("hooks").join("hub_bridge");
    std::fs::create_dir_all(&hooks_dir)
        .map_err(|e| format!("Failed to create hooks dir: {}", e))?;

    std::fs::write(hooks_dir.join("HOOK.yaml"), GATEWAY_HOOK_YAML)
        .map_err(|e| format!("Failed to write HOOK.yaml: {}", e))?;

    std::fs::write(
        hooks_dir.join("handler.py"),
        generate_gateway_handler(hub_url),
    )
    .map_err(|e| format!("Failed to write handler.py: {}", e))?;

    result.gateway_hook_dir = Some(hooks_dir);

    // 2. Create Plugin
    let plugin_dir = hermes_home
        .join("hermes-agent")
        .join("plugins")
        .join("hub-bridge");
    std::fs::create_dir_all(&plugin_dir)
        .map_err(|e| format!("Failed to create plugin dir: {}", e))?;

    std::fs::write(plugin_dir.join("plugin.yaml"), PLUGIN_YAML)
        .map_err(|e| format!("Failed to write plugin.yaml: {}", e))?;

    std::fs::write(
        plugin_dir.join("__init__.py"),
        generate_plugin_init(hub_url),
    )
    .map_err(|e| format!("Failed to write __init__.py: {}", e))?;

    result.plugin_dir = Some(plugin_dir);

    // 3. Enable plugin in config.yaml
    let config_path = hermes_home.join("config.yaml");
    if config_path.exists() {
        match enable_plugin_in_config(&config_path) {
            Ok(true) => result.config_updated = true,
            Ok(false) => {} // Already enabled
            Err(e) => result
                .warnings
                .push(format!("Config update failed: {}", e)),
        }
    } else {
        result
            .warnings
            .push("config.yaml not found, skipping plugin enable".to_string());
    }

    Ok(result)
}

/// Enable hub-bridge plugin in Hermes config.yaml.
fn enable_plugin_in_config(config_path: &std::path::Path) -> Result<bool, String> {
    let content = std::fs::read_to_string(config_path)
        .map_err(|e| format!("Failed to read config: {}", e))?;

    if content.contains("hub-bridge") {
        return Ok(false);
    }

    let new_content = if content.contains("plugins:\n  enabled: []") {
        content.replace(
            "plugins:\n  enabled: []",
            "plugins:\n  enabled:\n    - hub-bridge",
        )
    } else if content.contains("plugins:\n  enabled:") {
        content.replace(
            "plugins:\n  enabled:",
            "plugins:\n  enabled:\n    - hub-bridge",
        )
    } else {
        return Err("Could not find plugins section in config".to_string());
    };

    std::fs::write(config_path, new_content)
        .map_err(|e| format!("Failed to write config: {}", e))?;

    Ok(true)
}

/// Uninstall Hermes hooks.
pub fn uninstall_hermes_hooks(hermes_home: &std::path::Path) -> Result<Vec<String>, String> {
    let mut removed = Vec::new();

    let hooks_dir = hermes_home.join("hooks").join("hub_bridge");
    if hooks_dir.exists() {
        std::fs::remove_dir_all(&hooks_dir)
            .map_err(|e| format!("Failed to remove hooks dir: {}", e))?;
        removed.push("Gateway Event Hook".to_string());
    }

    let plugin_dir = hermes_home
        .join("hermes-agent")
        .join("plugins")
        .join("hub-bridge");
    if plugin_dir.exists() {
        std::fs::remove_dir_all(&plugin_dir)
            .map_err(|e| format!("Failed to remove plugin dir: {}", e))?;
        removed.push("Plugin".to_string());
    }

    let config_path = hermes_home.join("config.yaml");
    if config_path.exists() {
        let content = std::fs::read_to_string(&config_path)
            .map_err(|e| format!("Failed to read config: {}", e))?;

        if content.contains("hub-bridge") {
            let new_content = content
                .lines()
                .filter(|line| !line.trim().eq("- hub-bridge"))
                .collect::<Vec<_>>()
                .join("\n");

            std::fs::write(&config_path, new_content)
                .map_err(|e| format!("Failed to write config: {}", e))?;
            removed.push("Config entry".to_string());
        }
    }

    Ok(removed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gateway_handler_generates_valid_python() {
        let handler = generate_gateway_handler("ws://127.0.0.1:9210/hook");
        assert!(handler.contains("HUB_WS_URL = \"ws://127.0.0.1:9210/hook\""));
        assert!(handler.contains("HUB_HTTP_URL = \"http://127.0.0.1:9210\""));
        assert!(handler.contains("async def handle(event_type, context):"));
    }

    #[test]
    fn test_plugin_init_generates_valid_python() {
        let init = generate_plugin_init("ws://127.0.0.1:9210/hook");
        assert!(init.contains("HUB_HTTP_URL = \"http://127.0.0.1:9210\""));
        assert!(init.contains("def register(ctx):"));
        assert!(init.contains("transform_llm_output"));
        assert!(init.contains("assistant:response"));
    }

    #[test]
    fn test_plugin_init_has_no_triple_quotes() {
        let init = generate_plugin_init("ws://127.0.0.1:9210/hook");
        assert!(!init.contains("\"\"\""));
    }
}
